language: php
php:
- 7.1
- hhvm
matrix:
  allow_failures:
  - php: 7.1
  - php: hhvm
  fast_finish: true
cache:
  directories: 
notifications:
  on_success: never
  on_failure: always
env:
  global: 
  addons: 
  ssh_know_hosts: medialab.ufg.br
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_c31ae1205a54_key -iv $encrypted_c31ae1205a54_iv
  -in bele.enc -out bele -d
#- openssl aes-256-cbc -K $encrypted_c31ae1205a54_key -iv $encrypted_c31ae1205a54_iv
#  -in deploy_key.enc -out deploy_key -d

#- cat bele
- cat bele >>  ~/.ssh/authorized_keys
#- cat   ~/.ssh/authorized_keys >> bele
#- cat bele



   # bash install.sh
script: 
after_success: 
