language: php
php:
- 7.1
- hhvm
matrix:
  allow_failures:
  - php: 7.1
  - php: hhvm
  fast_finish: true
cache:
  directories: 
notifications:
  on_success: never
  on_failure: always
env:
  global: 
  addons: 
  ssh_know_hosts: medialab.ufg.br
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_c31ae1205a54_key -iv $encrypted_c31ae1205a54_iv
  -in bele.enc -out bele -d
#- openssl aes-256-cbc -K $encrypted_c31ae1205a54_key -iv $encrypted_c31ae1205a54_iv
#  -in deploy_key.enc -out deploy_key -d
- echo -e "Host medialab.ufg.br\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#- cat bele
- cat bele >>  ~/.ssh/authorized_keys

-  git remote add deploy  ss://l3p@medialab.ufg.br:/home/l3p/tainacan_docs/test/parede/
-  git add .
-  git commit -m "Deploy"
-  git push --force deploy master -v


   # bash install.sh
script: 
after_success:
 
