language: php

php:
- 7.1
- hhvm-3.21
- nightly

matrix:
  allow_failures:
    - php: 7.1
    - php: hhvm
  fast_finish: true

addons:
  - ssh_know_hosts: medialab.ufg.br
  
git:
  submodules: false    
  
 install:
  #- composer self-update
  #- composer install

script:
  #- ./vendor/bin/phpunit tests 
  
after_success:
- openssl aes-256-cbc -K $encrypted_c31ae1205a54_key -iv $encrypted_c31ae1205a54_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add  deploy_rsa
- echo -e "Host medialab.ufg.br\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#- ssh l3p@medialab.ufg.br git pull origin master /home/l3p/tainacan_docs/parede/
#- ssh l3p@medialab.ufg.br git init  /home/l3p/tainacan_docs/test/parede
#- ssh l3p@medialab.ufg.br git pull /home/l3p/tainacan_docs/test/parede
#testa
#- ssh l3p@medialab.ufg.br rm -r /home/l3p/tainacan_docs/test/parede
#- ssh l3p@medialab.ufg.br cd /home/l3p/tainacan_docs/test/parede
#- ssh l3p@medialab.ufg.br ls
#- ssh l3p@medialab.ufg.br git pull /home/l3p/tainacan_docs/test/parede/
#- ssh l3p@medialab.ufg.br git clone https://github.com/walisonjose/parede.git /home/l3p/tainacan_docs/test/parede/
#- git remote add deploy ssh://l3p@medialab.ufg.br:/home/l3p/tainacan_docs/test/parede/
#- git add .
#- git commit -m "Deploy"
#- git push  deploy master -v
#- git fetch --all
#- git pull deploy master
#- git push deploy master
#- git pull 
#- scp -r * l3p@medialab.ufg.br:/home/l3p/tainacan_docs/test/parede/
#testando
#- ssh l3p@medialab.ufg.br git pull /home/l3p/tainacan_docs/test/parede/
#asdasdsad

cache:
  directories:
  #- vendor
  #- $HOME/.cache/composer
   
 notifications:
  email:
    on_success: never
    on_failure: always
  
  env:
  global:
  
  
