language: php
php:
- 7.1
- hhvm
matrix:
  allow_failures:
  - php: 7.1
  - php: hhvm
  fast_finish: true
cache:
  directories: 
notifications:
  on_success: never
  on_failure: always
env:
  global: 
  addons: 
  ssh_know_hosts: medialab.ufg.br
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_c31ae1205a54_key -iv $encrypted_c31ae1205a54_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add  deploy_rsa
- echo -e "Host medialab.ufg.br\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

#- ssh l3p@medialab.ufg.br git pull origin master /home/l3p/tainacan_docs/parede/

#ssh l3p@medialab.ufg.br mkdir /home/l3p/travis/
- git remote add deploy ssh://l3p@medialab.ufg.br:/home/l3p/tainacan_docs/parede/
#- git add .
#- git commit -m "Deploy"
#- git push  deploy master -v
- git fetch deploy master
- git pull  deploy master
#- git push deploy master



#- ssh l3p@medialab.ufg.br
script: 
after_success: 
