language: php
php:
- 7.1
- hhvm
matrix:
  allow_failures:
  - php: 7.1
  - php: hhvm
  fast_finish: true
cache:
  directories: 
notifications:
  on_success: never
  on_failure: always
env:
  global:
  
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
 
 addons: 
  ssh_know_hosts: medialab.ufg.br
  apt:
        packages:
            - sshpass
git:
  submodules: false
before_install:

script: 
after_success: 

ssh l3p@medialab.ufg.br



